# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake3

# The command to remove a file.
RM = /usr/bin/cmake3 -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/idan/vcuda-controller

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/idan/vcuda-controller

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake3 --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/idan/vcuda-controller/CMakeFiles /home/idan/vcuda-controller/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/idan/vcuda-controller/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named nvml-monitor

# Build rule for target.
nvml-monitor: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nvml-monitor
.PHONY : nvml-monitor

# fast build rule for target.
nvml-monitor/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvml-monitor.dir/build.make CMakeFiles/nvml-monitor.dir/build
.PHONY : nvml-monitor/fast

#=============================================================================
# Target rules for targets named cuda-control

# Build rule for target.
cuda-control: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cuda-control
.PHONY : cuda-control

# fast build rule for target.
cuda-control/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuda-control.dir/build.make CMakeFiles/cuda-control.dir/build
.PHONY : cuda-control/fast

src/cuda_originals.o: src/cuda_originals.c.o

.PHONY : src/cuda_originals.o

# target to build an object file
src/cuda_originals.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuda-control.dir/build.make CMakeFiles/cuda-control.dir/src/cuda_originals.c.o
.PHONY : src/cuda_originals.c.o

src/cuda_originals.i: src/cuda_originals.c.i

.PHONY : src/cuda_originals.i

# target to preprocess a source file
src/cuda_originals.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuda-control.dir/build.make CMakeFiles/cuda-control.dir/src/cuda_originals.c.i
.PHONY : src/cuda_originals.c.i

src/cuda_originals.s: src/cuda_originals.c.s

.PHONY : src/cuda_originals.s

# target to generate assembly for a file
src/cuda_originals.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuda-control.dir/build.make CMakeFiles/cuda-control.dir/src/cuda_originals.c.s
.PHONY : src/cuda_originals.c.s

src/hijack_call.o: src/hijack_call.c.o

.PHONY : src/hijack_call.o

# target to build an object file
src/hijack_call.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuda-control.dir/build.make CMakeFiles/cuda-control.dir/src/hijack_call.c.o
.PHONY : src/hijack_call.c.o

src/hijack_call.i: src/hijack_call.c.i

.PHONY : src/hijack_call.i

# target to preprocess a source file
src/hijack_call.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuda-control.dir/build.make CMakeFiles/cuda-control.dir/src/hijack_call.c.i
.PHONY : src/hijack_call.c.i

src/hijack_call.s: src/hijack_call.c.s

.PHONY : src/hijack_call.s

# target to generate assembly for a file
src/hijack_call.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuda-control.dir/build.make CMakeFiles/cuda-control.dir/src/hijack_call.c.s
.PHONY : src/hijack_call.c.s

src/loader.o: src/loader.c.o

.PHONY : src/loader.o

# target to build an object file
src/loader.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvml-monitor.dir/build.make CMakeFiles/nvml-monitor.dir/src/loader.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuda-control.dir/build.make CMakeFiles/cuda-control.dir/src/loader.c.o
.PHONY : src/loader.c.o

src/loader.i: src/loader.c.i

.PHONY : src/loader.i

# target to preprocess a source file
src/loader.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvml-monitor.dir/build.make CMakeFiles/nvml-monitor.dir/src/loader.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuda-control.dir/build.make CMakeFiles/cuda-control.dir/src/loader.c.i
.PHONY : src/loader.c.i

src/loader.s: src/loader.c.s

.PHONY : src/loader.s

# target to generate assembly for a file
src/loader.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvml-monitor.dir/build.make CMakeFiles/nvml-monitor.dir/src/loader.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuda-control.dir/build.make CMakeFiles/cuda-control.dir/src/loader.c.s
.PHONY : src/loader.c.s

src/nvml_entry.o: src/nvml_entry.c.o

.PHONY : src/nvml_entry.o

# target to build an object file
src/nvml_entry.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuda-control.dir/build.make CMakeFiles/cuda-control.dir/src/nvml_entry.c.o
.PHONY : src/nvml_entry.c.o

src/nvml_entry.i: src/nvml_entry.c.i

.PHONY : src/nvml_entry.i

# target to preprocess a source file
src/nvml_entry.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuda-control.dir/build.make CMakeFiles/cuda-control.dir/src/nvml_entry.c.i
.PHONY : src/nvml_entry.c.i

src/nvml_entry.s: src/nvml_entry.c.s

.PHONY : src/nvml_entry.s

# target to generate assembly for a file
src/nvml_entry.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuda-control.dir/build.make CMakeFiles/cuda-control.dir/src/nvml_entry.c.s
.PHONY : src/nvml_entry.c.s

src/register.o: src/register.c.o

.PHONY : src/register.o

# target to build an object file
src/register.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvml-monitor.dir/build.make CMakeFiles/nvml-monitor.dir/src/register.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuda-control.dir/build.make CMakeFiles/cuda-control.dir/src/register.c.o
.PHONY : src/register.c.o

src/register.i: src/register.c.i

.PHONY : src/register.i

# target to preprocess a source file
src/register.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvml-monitor.dir/build.make CMakeFiles/nvml-monitor.dir/src/register.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuda-control.dir/build.make CMakeFiles/cuda-control.dir/src/register.c.i
.PHONY : src/register.c.i

src/register.s: src/register.c.s

.PHONY : src/register.s

# target to generate assembly for a file
src/register.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvml-monitor.dir/build.make CMakeFiles/nvml-monitor.dir/src/register.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuda-control.dir/build.make CMakeFiles/cuda-control.dir/src/register.c.s
.PHONY : src/register.c.s

tools/monitor_dockernized.o: tools/monitor_dockernized.c.o

.PHONY : tools/monitor_dockernized.o

# target to build an object file
tools/monitor_dockernized.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvml-monitor.dir/build.make CMakeFiles/nvml-monitor.dir/tools/monitor_dockernized.c.o
.PHONY : tools/monitor_dockernized.c.o

tools/monitor_dockernized.i: tools/monitor_dockernized.c.i

.PHONY : tools/monitor_dockernized.i

# target to preprocess a source file
tools/monitor_dockernized.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvml-monitor.dir/build.make CMakeFiles/nvml-monitor.dir/tools/monitor_dockernized.c.i
.PHONY : tools/monitor_dockernized.c.i

tools/monitor_dockernized.s: tools/monitor_dockernized.c.s

.PHONY : tools/monitor_dockernized.s

# target to generate assembly for a file
tools/monitor_dockernized.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nvml-monitor.dir/build.make CMakeFiles/nvml-monitor.dir/tools/monitor_dockernized.c.s
.PHONY : tools/monitor_dockernized.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... cuda-control"
	@echo "... nvml-monitor"
	@echo "... src/cuda_originals.o"
	@echo "... src/cuda_originals.i"
	@echo "... src/cuda_originals.s"
	@echo "... src/hijack_call.o"
	@echo "... src/hijack_call.i"
	@echo "... src/hijack_call.s"
	@echo "... src/loader.o"
	@echo "... src/loader.i"
	@echo "... src/loader.s"
	@echo "... src/nvml_entry.o"
	@echo "... src/nvml_entry.i"
	@echo "... src/nvml_entry.s"
	@echo "... src/register.o"
	@echo "... src/register.i"
	@echo "... src/register.s"
	@echo "... tools/monitor_dockernized.o"
	@echo "... tools/monitor_dockernized.i"
	@echo "... tools/monitor_dockernized.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

